### ISSUE TITLE
Cannot find module 'dotenv-safe/config'

### ISSUE THREAD

**Issue by denizdogan** [rolodato/dotenv-safe#29]
Since the update to 5.0.0, I noticed you removed the config.js file and integrated it into index.js. This breaks for me (and probably a lot of other people) who used to run:

```
node -r dotenv-safe/config app.js
```

This wasn't mentioned in the changelog but I would love it if you would consider reintroducing config.js so that I won't have to change the way we run our applications. :)

**Comment by rolodato** [comment]
Seems like I accidentally nuked it in the commit, which is why it doesn't show up in the changelog. I'll fix it today as soon as I can. Sorry about that!

**Comment by rolodato** [comment]
5.0.1 has been released with the original config.js again. Thanks!
